dist: trusty
language: java
jdk:
- openjdk8

addons:
  sonarcloud:
    organization: "cptpackage"
    token:
      secure: "232155acd16223afe30bf6a28399e44baf2701a7"

script:
- ant build
- sonar-scanner